name: WPScan Security Scan

on:
  workflow_dispatch:

jobs:
  wpscan:
    runs-on: ubuntu-latest

    steps:
      - name: Run WPScan
        uses: WTFender/wpscan-action@v1.0
        with:
          url: 'https://smkdtbs.sch.id'
          token: ${{ secrets.WPSCAN_API_TOKEN }}
          usernames: 'adminsmkdtbs,humas_smkdt'
          passwords: '/github/workspace/wordlists/combined_wordlist.txt'
          random_user_agent: true
          max_threads: 5
