name: WPScan Security Scan

on:
  workflow_dispatch:

jobs:
  wpscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Cache Directory
        run: mkdir -p ~/.wpscan-cache

      - name: Run WPScan
        uses: docker://wpscanteam/wpscan:latest
        with:
          args: >
            --no-update
            --url https://smkdtbs.sch.id
            --usernames adminsmkdtbs,humas_smkdt
            --passwords /github/workspace/wordlists/combined_wordlist.txt
            --api-token ${{ secrets.WPSCAN_API_TOKEN }}
            --random-user-agent
            --max-threads 5
            --format cli-no-color
